### ISSUE TITLE
docker 运行失败

### ISSUE THREAD

**Issue by windflee** [TsinghuaAI/CPM-2-Finetune#10]
docker: Error response from daemon: OCI runtime create failed: invalid mount {Destination::/root/cogview2 Type:bind Source:/var/lib/docker/volumes/2684685af4d426ae564e1233e62e8d6beb61a6856907021d7f26d3ddb2267ffa/_data Options:[rbind]}: mount destination :/root/cogview2 not absolute: unknown.
ERRO[0003] error waiting for container: context canceled 
是哪里的问题了？

**Comment by t1101675** [comment]
是 docker 镜像的问题，现在已经修改了，可以重新拉取 1.1 版本。
