### ISSUE TITLE
Can CPM-2 run in playground model, any prompt hint?

### ISSUE THREAD

**Issue by qhduan** [TsinghuaAI/CPM-2-Finetune#12]
For example, like https://studio.ai21.com/ 's 'explain a word'

```
What does the word "link" mean in the following sentence?
Sentence: The excavation machine malfunctioned due to a broken link.
Meaning: a ring or loop in a chain.

What does the word "bank on" mean in the following sentence?
Sentence: I was banking on my team winning the next game as well.
Meaning: to depend on something.

What does the word "drop" mean in the following sentence?
Sentence: the drop in subscriptions in May was cause for alarm.
Meaning:
```

this prompt should be send to encoder or decoder?

any special token we have to use in zh or zh_en model?

or CPM-2 don't support playground like this?

**Comment by t1101675** [comment]
This prompt should be sent to encoder and we think it would be better if you concatenate <s_0> token after `...Meaning:`. But CPM-2 is trained with masked language modeling and may not do well in this kind of prompt task. We recommend trying CPM-1 which is trained with language modeling:  https://github.com/TsinghuaAI/CPM-1-Generate , https://github.com/TsinghuaAI/CPM-1-Finetune
