### ISSUE TITLE
请问2张A100-40G能跑吗

### ISSUE THREAD

**Issue by 2020zyc** [TsinghuaAI/CPM-2-Finetune#15]
如题，4张没问题，但是觉得gpu利用率不高，所以想设置2gpu；
遇到错误，attention某个权重不在第0个statedict里面；如下：
![image](https://user-images.githubusercontent.com/7539692/131964642-d1fe83e2-ac95-4067-982c-9d0667bdcd3b.png)

![image](https://user-images.githubusercontent.com/7539692/131965556-355a826b-8a56-472a-bfee-a71c89bb2d47.png)

![image](https://user-images.githubusercontent.com/7539692/131965452-9dd49338-f6a0-41bc-935f-b6690e277462.png)

这个错误来自deepspeed在合并statedict时，会有个sanity_check(ckpt_list[0])，即检查第0个statedict是否含有attention相关的几个参数；
请问有解决方案吗？考虑注释掉sanity_check，不知是否可行？

**Comment by 2020zyc** [comment]
@t1101675 谢谢

**Comment by t1101675** [comment]
您好，如果需要将模型并行从4改为2的话，可以使用我们提供的转换脚本 https://github.com/TsinghuaAI/CPM-1-Generate/blob/main/change_mp.py。deepspeed 的脚本可能会有一些坑。

**Comment by 2020zyc** [comment]
> 您好，如果需要将模型并行从4改为2的话，可以使用我们提供的转换脚本 [https://github.com/TsinghuaAI/CPM-1-Generate/blob/main/change_mp.py。deepspeed](https://github.com/TsinghuaAI/CPM-1-Generate/blob/main/change_mp.py%E3%80%82deepspeed) 的脚本可能会有一些坑。

你好，按照上述方法可以成功切分。我使用双语模型，将原来的4个模型文件，成功切分成6个。双语模型词汇量51968，加载6个新模型文件时，报错51968无法平分到6个gpu(51968/6=8661.3333)。51968能被2、4、8整除。

请问有处理方法吗？我手动加几个词凑成6的倍数？

**Comment by t1101675** [comment]
这个应该不行，切分模型的时候模型的份数要保证是2的幂次，否则 embedding 的维度可能会对不上。这样设置的原因是一般 GPU 的数量配置都是2的幂次。

**Comment by 2020zyc** [comment]
> 这个应该不行，切分模型的时候模型的份数要保证是2的幂次，否则 embedding 的维度可能会对不上。这样设置的原因是一般 GPU 的数量配置都是2的幂次。

👌

还有个错误，我把4个变成8个，加载的时候报错了，参数大小不匹配。都是这样的：checkpoint是[2a, b]，但是模型是 [a, 2b]，具体如下图；是否是change_mp有问题？
![image](https://user-images.githubusercontent.com/7539692/132293687-92eda9ab-941a-49e6-badd-5afd83cc2e6f.png)

**Comment by 2020zyc** [comment]
还有个问题请教：我直接加载原来4个模型文件到8块gpu上，好像也能跑；这样和先转换成8个模型文件，再加载有什么区别？

**Comment by t1101675** [comment]
前者自动进行了进程为2的数据并行，而模型并行数为4，也就是前四章卡和后四张卡保存着相同的模型。如果转换为8个文件，模型并行数量为8，数据并行数为1。相关概念更详细的解释可以参考 https://www.zhihu.com/question/53851014

**Comment by 2020zyc** [comment]
> 前者自动进行了进程为2的数据并行，而模型并行数为4，也就是前四章卡和后四张卡保存着相同的模型。如果转换为8个文件，模型并行数量为8，数据并行数为1。相关概念更详细的解释可以参考 https://www.zhihu.com/question/53851014

哦哦， 理解。
麻烦帮忙看看倒数第二个问题，即转换成8个文件后，加载参数size不匹配的错误。谢谢

**Comment by 2020zyc** [comment]
> > 这个应该不行，切分模型的时候模型的份数要保证是2的幂次，否则 embedding 的维度可能会对不上。这样设置的原因是一般 GPU 的数量配置都是2的幂次。
> 
> 👌
> 
> 还有个错误，我把4个变成8个，加载的时候报错了，参数大小不匹配。都是这样的：checkpoint是[2a, b]，但是模型是 [a, 2b]，具体如下图；是否是change_mp有问题？
> ![image](https://user-images.githubusercontent.com/7539692/132293687-92eda9ab-941a-49e6-badd-5afd83cc2e6f.png)

你好，请问上述变成8个模型文件后，报错size不匹配，有解决方案吗，我尝试修改change_mp，没成功。多谢 @t1101675

**Comment by 2020zyc** [comment]
我修改了change_mp，已经可以跑8个文件的。
前面的问题是因为 cmp2的模型并行 对于tensor size=2 的weight 有两种模式，分别是行并行和列并行（具体例子见mpu/transformer_enc_dec.py/ParallelAttention(class)）。
两种并行方式分别对行和列进行切分，不同weight可能使用不同模式。因此，在从4文件变到8文件的时候，需要对不同weight设置不同的切分方式。
我是从上面的错误发现是两类weight分别对应行、列切分的，因此只需要在change_mp里面加条件判定切分方式即可，修改起来还是比较容易的。
change_mp的修改如下：
![image](https://user-images.githubusercontent.com/7539692/132482457-8246fcb6-f103-42f3-aa7b-1c517be8d398.png)

**Comment by jiangliqin** [comment]
@2020zyc 请问把模型从4变成8，按照修改的change_mp，最终跑完结果如何呢？
