### ISSUE TITLE
attention.dense.weight not found when prompt fine tuning

### ISSUE THREAD

**Issue by luotongml** [TsinghuaAI/CPM-2-Finetune#16]
您好，我使用了100000的中文模型，进行prompt tuning。数据集用的是adgen，但是加载模型时出现了attention.dense.weight not found的问题如下。请您帮忙协助看下，谢谢。

在redhat上运行指令为：
bash scripts/prompt/finetune_cpm2_adgen.sh

cmd = /home/anaconda/anaconda3/bin/python -u -m deepspeed.launcher.launch --world_info=eyJxxx --master_addr=192.x.x.x --master_port=29500 /home/tluo/CPM-2-Finetune/finetune_cpm2.py --model-config /home/tluo/CPM-2-Finetune/configs/model/cpm2_config.json --model-parallel-size 4 --batch-size 16 --eval-batch-size 64 --gradient-accumulation-steps 2 --train-iters -1 --save /home/tluo/CPM-2-Finetune/results/adgen/cpm2_prompt_lr0.005const_G2/ --log-file /home/tluo/CPM-2-Finetune/results/adgen/cpm2_prompt_lr0.005const_G2//log.txt --load /home/tluo/wudao --data-path /home/tluo/data/adgen/data/processed --data-ext .jsonl --data-name adgen --distributed-backend nccl --lr 0.005 --no-load-optim --lr-decay-style constant --weight-decay 1e-2 --clip-grad 1.0 --warmup 0.0 --tokenizer-path /home/tluo/CPM-2-Finetune/bpe_cn --save-interval 100000 --eval-interval 100 --eval-iters 10 --log-interval 10 --checkpoint-activations --deepspeed-activation-checkpointing --fp16 --deepspeed --deepspeed_config /home/tluo/CPM-2-Finetune/configs/deepspeed/ds_adgen_prompt.json --do-train --do-valid --prompt-tune --prompt-config /home/tluo/CPM-2-Finetune/configs/prompt/adgen/adgen_10_0_0.json --epochs 1 --top-p 0.9 --top-k 40

下面是出错后的相关信息

[2021-09-03 17:04:15,677] [INFO] [state_dict_factory.py:165:check_ckpt_list] checkpoint file list: ['/home/tluo/wudao/100000/mp_rank_00_model_states.pt', '/home/tluo/wudao/100000/mp_rank_01_model_states.pt', '/home/tluo/wudao/100000/mp_rank_02_model_states.pt', '/home/tluo/wudao/100000/mp_rank_03_model_states.pt']
[2021-09-03 17:04:17,406] [INFO] [state_dict_factory.py:56:load] mp_world_size: 2, mp_rank: 1, module_key: auto
[2021-09-03 17:04:20,402] [INFO] [state_dict_factory.py:56:load] mp_world_size: 2, mp_rank: 0, module_key: auto
Traceback (most recent call last):
  File "/home/tluo/CPM-2-Finetune/finetune_cpm2.py", line 687, in <module>
    main()
  File "/home/tluo/CPM-2-Finetune/finetune_cpm2.py", line 670, in main
    model, optimizer, lr_scheduler = setup_model_and_optimizer(args, tokenizer.vocab_size, ds_config, prompt_config)
  File "/home/tluo/CPM-2-Finetune/utils.py", line 231, in setup_model_and_optimizer
    args.iteration = load_checkpoint(model, optimizer, lr_scheduler, args)
  File "/home/tluo/CPM-2-Finetune/utils.py", line 502, in load_checkpoint
    load_lr_scheduler_states=args.load_lr_scheduler_states)
  File "/home/tluo/.local/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 1919, in load_checkpoint
    load_module_only=load_module_only)
  File "/home/tluo/.local/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 1952, in _load_checkpoint
    load_path, checkpoint, _ = sd_loader.load(self.mp_world_size, mp_rank, is_pipe_parallel=is_pipe_parallel)
  File "/home/tluo/.local/lib/python3.7/site-packages/deepspeed/runtime/state_dict_factory.py", line 97, in load
    quantize_bits, quantize_groups, mlp_extra_grouping)
  File "/home/tluo/.local/lib/python3.7/site-packages/deepspeed/runtime/state_dict_factory.py", line 316, in merge_state_dict
    self.sanity_check(self.ckpt_list[0])
  File "/home/tluo/.local/lib/python3.7/site-packages/deepspeed/runtime/state_dict_factory.py", line 451, in sanity_check
    assert check_key_exist(key, self.get_module(sd)), f'key: {key} is not found in the checkpoint {ckpt_file_name}'
AssertionError: key: attention.dense.weight is not found in the checkpoint /home/tluo/wudao/100000/mp_rank_00_model_states.pt

**Comment by t1101675** [comment]
您好，这应该是 deepspeed 版本的问题，我们在 README 里面更新的版本要求，您可以再看下~

**Comment by luotongml** [comment]
谢谢您及时的回复。我对deepspeed不是非常熟悉，只是按照readme里要求把deepspeed/runtime/zero/stage1.py替换为repo里面的stage1.py。然而，仍然会出现 key: attention.dense.weight is not found 的问题。需要我把stage2.py和stage3.py同样做修改吗？错误信息还是如下：

AssertionError: key: attention.dense.weight is not found in the checkpoint /home/tluo/wudao/100000/mp_rank_00_model_states.pt

谢谢

**Comment by t1101675** [comment]
麻烦您核对一下 deeospeed 的版本，我们在 readmee 里面还写了版本要求

**Comment by luotongml** [comment]
嗯，deepspeed是0.5.1。从readme看以为可以只修改stage1.py 就可以工作。但看起来还是报错。

**Comment by t1101675** [comment]
请问您有没有将版本降到 readme 里面提到的 0.3.9？

**Comment by luotongml** [comment]
没有，我回头试一下docker吧，并告知您运行情况。不过我是根据这个描述做的修改。

https://github.com/TsinghuaAI/CPM-2-Finetune/issues/11

“We have reproduced the problem with deepspeed(v0.5.0). We think the problem is caused by a bug in deepspeed which we have fixed in the docker we provided.

Specifically, there is a copy operation from the fp32 states of the optimizer to the fp16 states of the model in the deepspeed zero optimizer. This works well when optimizer states (zero_pp_rank_0_mp_rank_01_optim_states.pt) are loaded. But when the optimizer states are not provided, the fp32 states in the optimizer are randomly initialized and overide the pre-trained states in the model. This is where the problem occurs.

To fix the problem, we recommend you to use our docker directly. But if you would like to use the latest deepspeed, you can fix the bug by adding a few lines of code in deepspeed/runtime/zero/stage1.py. We provide the fixed stage1.py in our repository. This file is based on deepspeed (v0.3.9), but other versions should be similar. We mark the lines that need to be modified with CPM: HACK. You can locate these lines by just searching CPM: HACK.”

**Comment by t1101675** [comment]
您可以看一下这个 issue，跟您遇到的问题并不一样。这个修改确实要做，但是您遇到的问题是另一回事，需要把版本降低到0.3.9

**Comment by luotongml** [comment]
改用readme中提供的docker，为了适配A40 GPU,  使用pytorch0.9，cuda11.1，

然而仍然得到如下importError：

Traceback (most recent call last):                                                                                          
  File "/mnt2/CPM-2-Finetune/finetune_cpm2.py", line 687, in <module>                                                       
    main()                                                                                                                  
  File "/mnt2/CPM-2-Finetune/finetune_cpm2.py", line 670, in main                                                           
    model, optimizer, lr_scheduler = setup_model_and_optimizer(args, tokenizer.vocab_size, ds_config, prompt_config)        
  File "/mnt2/CPM-2-Finetune/utils.py", line 219, in setup_model_and_optimizer                                              
    model, optimizer, _, lr_scheduler = deepspeed.initialize(                                                               
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/__init__.py", line 110, in initialize                              
    engine = DeepSpeedEngine(args=args,                                                                                     
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 198, in __init__                          
    util_ops = UtilsBuilder().load()                                                                                        
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 178, in load                      
    return importlib.import_module(self.absolute_name())                                                                    
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module                                         
    return _bootstrap._gcd_import(name[level:], package, level)                                                             
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import                                                           
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load                                                         
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked                                                
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked                                                         
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec                                                       
  File "<frozen importlib._bootstrap_external>", line 1101, in create_module                                                
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                              
ImportError: /opt/conda/lib/python3.8/site-packages/deepspeed/ops/utils_op.cpython-38-x86_64-linux-gnu.so: undefined symbol:
 _ZNK2at6Tensor10contiguousEN3c1012MemoryFormatE

**Comment by luotongml** [comment]
A further ds_report 如下，deepspeed的和pytorch版本问题？

--------------------------------------------------                                                   
DeepSpeed C++/CUDA extension op report                                                               
--------------------------------------------------                                                   
NOTE: Ops not installed will be just-in-time (JIT) compiled at                                       
      runtime if needed. Op compatibility means that your system                                     
      meet the required dependencies to JIT install the op.                                          
--------------------------------------------------                                                   
JIT compiled ops requires ninja                                                                      
ninja .................. [OKAY]                                                                      
--------------------------------------------------                                                   
op name ................ installed .. compatible                                                     
--------------------------------------------------                                                   
cpu_adam ............... [YES] ...... [OKAY]                                                         
fused_adam ............. [YES] ...... [OKAY]                                                         
fused_lamb ............. [YES] ...... [OKAY]                                                         
 [WARNING]  sparse_attn requires CUDA version 10.1+, does not currently support >=11 or <10.1        
sparse_attn ............ [YES] ...... [NO]                                                           
transformer ............ [YES] ...... [OKAY]                                                         
stochastic_transformer . [YES] ...... [OKAY]                                                         
utils .................. [YES] ...... [OKAY]                                                         
--------------------------------------------------                                                   
DeepSpeed general environment info:                                                                  
torch install path ............... ['/opt/conda/lib/python3.8/site-packages/torch']                  
torch version .................... 1.9.0+cu111                                                       
torch cuda version ............... 11.1                                                              
nvcc version ..................... 10.2                                                              
deepspeed install path ........... ['/opt/conda/lib/python3.8/site-packages/deepspeed']              
deepspeed info ................... 0.3.9+59e4dbb, 59e4dbb, master                                    
deepspeed wheel compiled w. ...... torch 1.7, cuda 10.2

**Comment by t1101675** [comment]
应该是和版本有关

**Comment by luotongml** [comment]
因为a40需要cuda支持sm_86, 所以我把原始docker升级cuda到11.1，用11.1和torch重新升级安装了deepspeed，之前的问题没有了。

但是因为我的机器是只有一台机器，有3个A40（不是4或8个），而100000目录下模型mp_size 是4，有什么办法能够让这个prompt tuning跑起来呢？如果使用1worker，2GPU的话会报出tensor shape不匹配的问题。

谢谢。


另外，我的修改安装ds_report如下，供其他同学参考。


ds_report                                  
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
sparse_attn ............ [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/opt/conda/lib/python3.8/site-packages/torch']
torch version .................... 1.9.0+cu111
torch cuda version ............... 11.1
nvcc version ..................... 11.1
deepspeed install path ........... ['/opt/conda/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.3.9, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.9, cuda 11.1

**Comment by t1101675** [comment]
我们提供了一个转换模型并行度的脚本 https://github.com/TsinghuaAI/CPM-1-Generate/blob/main/change_mp.py，可以参考~

**Comment by luotongml** [comment]
使用这个脚本，change 100000 mp_size 为2，
python change_mp.py  /mnt2/wudao 2

然后修改
NUM_WORKERS=1
NUM_GPUS_PER_WORKER=2
MP_SIZE=2
CKPT_PATH="/mnt2/wudao_MP2"

运行
 bash scripts/prompt/finetune_cpm2_adgen.sh
得到如下错误。是否我这些运行参数修改有问题？看起来shape 都不匹配。

RuntimeError: Error(s) in loading state_dict for EncDecModel:
        size mismatch for lm_head.weight: copying a param with shape torch.Size([6560, 8192]) from checkpoint, the shape in current model is torch.Size([13120, 4096]).
        size mismatch for encoder.blocks.0.self_attn.self_attn.project.weight: copying a param with shape torch.Size([3072, 8192]) from checkpoint, the shape in current model is torch.Size([6144, 4096]).
        size mismatch for encoder.blocks.0.ff.dense_relu_dense.wi_0.weight: copying a param with shape torch.Size([2560, 8192]) from checkpoint, the shape in current model is torch.Size([5120, 4096]).
        size mismatch for encoder.blocks.0.ff.dense_relu_dense.wi_1.weight: copying a param with shape torch.Size([2560, 8192]) from checkpoint, the shape in current model is torch.Size([5120, 4096]).
        size mismatch for encoder.blocks.1.self_attn.self_attn.project.weight: copying a param with shape torch.Size([3072, 8192]) from checkpoint, the shape in current model is torch.Size([6144, 4096]).
        size mismatch for encoder.blocks.1.ff.dense_relu_dense.wi_0.weight: copying a param with shape torch.Size([2560, 8192]) from checkpoint, the shape in current model is torch.Size([5120, 4096]).
        size mismatch for encoder.blocks.1.ff.dense_relu_dense.wi_1.weight: copying a param with shape torch.Size([2560, 8192]) from checkpoint, the shape in current model is torch.Size([5120, 4096]).
        size mismatch for encoder.blocks.2.self_attn.self_attn.project.weight: copying a param with shape torch.Size([3072, 8192]) from checkpoint, the shape in current model is torch.Size([6144, 4096]).
        size mismatch for encoder.blocks.2.ff.dense_relu_dense.wi_0.weight: copying a param with shape torch.Size([2560, 8192]) from checkpoint, the shape in current model is torch.Size([5120, 4096]).

**Comment by 2020zyc** [comment]
> 使用这个脚本，change 100000 mp_size 为2，
> python change_mp.py /mnt2/wudao 2
> 
> 然后修改
> NUM_WORKERS=1
> NUM_GPUS_PER_WORKER=2
> MP_SIZE=2
> CKPT_PATH="/mnt2/wudao_MP2"
> 
> 运行
> bash scripts/prompt/finetune_cpm2_adgen.sh
> 得到如下错误。是否我这些运行参数修改有问题？看起来shape 都不匹配。
> 
> RuntimeError: Error(s) in loading state_dict for EncDecModel:
> size mismatch for lm_head.weight: copying a param with shape torch.Size([6560, 8192]) from checkpoint, the shape in current model is torch.Size([13120, 4096]).
> size mismatch for encoder.blocks.0.self_attn.self_attn.project.weight: copying a param with shape torch.Size([3072, 8192]) from checkpoint, the shape in current model is torch.Size([6144, 4096]).
> size mismatch for encoder.blocks.0.ff.dense_relu_dense.wi_0.weight: copying a param with shape torch.Size([2560, 8192]) from checkpoint, the shape in current model is torch.Size([5120, 4096]).
> size mismatch for encoder.blocks.0.ff.dense_relu_dense.wi_1.weight: copying a param with shape torch.Size([2560, 8192]) from checkpoint, the shape in current model is torch.Size([5120, 4096]).
> size mismatch for encoder.blocks.1.self_attn.self_attn.project.weight: copying a param with shape torch.Size([3072, 8192]) from checkpoint, the shape in current model is torch.Size([6144, 4096]).
> size mismatch for encoder.blocks.1.ff.dense_relu_dense.wi_0.weight: copying a param with shape torch.Size([2560, 8192]) from checkpoint, the shape in current model is torch.Size([5120, 4096]).
> size mismatch for encoder.blocks.1.ff.dense_relu_dense.wi_1.weight: copying a param with shape torch.Size([2560, 8192]) from checkpoint, the shape in current model is torch.Size([5120, 4096]).
> size mismatch for encoder.blocks.2.self_attn.self_attn.project.weight: copying a param with shape torch.Size([3072, 8192]) from checkpoint, the shape in current model is torch.Size([6144, 4096]).
> size mismatch for encoder.blocks.2.ff.dense_relu_dense.wi_0.weight: copying a param with shape torch.Size([2560, 8192]) from checkpoint, the shape in current model is torch.Size([5120, 4096]).

这个我解决了，能成功跑起来，应该没问题。参考close issue 2块A100 问题

**Comment by luotongml** [comment]
@2020zyc 感谢您的建议，我看了下，有几个疑问：
1. 您的code snippet修改看起来是把MP_SIZE从默认的4增加到8或更多的场景，而我希望是把MP_SIZE能够减少到2或者1的场景（从而我的单机2GPU可以跑起来），如果您能提供相关code snippet就非常有帮助了。
2. 我注意到我报的错误日志里的shape mismatch都来自于self_attn.project.weight，dense_relu_dense.wi_0.weight，因此如果按照您的issue的code snippet中修改dense.weight, wo.weight, relative_attention_bias.weight 应该不会有帮助的。

请您帮我解惑，谢谢

**Comment by 2020zyc** [comment]
> @2020zyc 感谢您的建议，我看了下，有几个疑问：
> 
> 1. 您的code snippet修改看起来是把MP_SIZE从默认的4增加到8或更多的场景，而我希望是把MP_SIZE能够减少到2或者1的场景（从而我的单机2GPU可以跑起来），如果您能提供相关code snippet就非常有帮助了。
> 2. 我注意到我报的错误日志里的shape mismatch都来自于self_attn.project.weight，dense_relu_dense.wi_0.weight，因此如果按照您的issue的code snippet中修改dense.weight, wo.weight, relative_attention_bias.weight 应该不会有帮助的。
> 
> 请您帮我解惑，谢谢

是我没注意到你的场景。不过应该是类似的问题吧，都是 你自己生成的tensor shape是[a,2b]，模型要求[2a,b]，或者反过来；

你说的第二点，我遇到过，对于我的场景（变成4、8）来说，原来change_mp是在dim 0（还是dim 1来着）切分，我改成dim 1（或者dim 0），之前报错size不匹配的tensor就变正确了，而原来size正确匹配的tensor就变成不匹配了，也就是会冒出你提到的那些tensor的size不匹配（原来没修改前是正确的）；

所以我才根据错误加上if else的判断，用来区分哪些应该在dim 0切分，哪些在dim 1切分，然后就没问题了；

你的问题是合并成2个甚至1个，1个应该不会有问题吧；2个的话，你上面的错也是chang_mp把所有tensor都按某个dim（比如dim0）合并了，你可以试试改成另一个dim（比如dim1），然后你应该会发现上面报错的tensor对了，但是又出现上面没报错的tensor反而报错了；就是因为要区分哪些tensor应该怎么合并

以上是我根据切分成8模型文件的经验，可以试试

**Comment by luotongml** [comment]
@2020zyc 谢谢您有探索性的建议，我这两天找时间尝试下把结果报给大家。 谢谢
