### ISSUE TITLE
bug? save_zero

### ISSUE THREAD

**Issue by 2020zyc** [TsinghuaAI/CPM-2-Finetune#17]
保存模型报错，说是没有 save_zero 这个参数；
我看model经过deepspeed封装，我使用你们提供的镜像跑，因此也是用镜像里面的deepspeed；
![image](https://user-images.githubusercontent.com/7539692/132815824-872a9a75-f68f-4862-974a-29d72212d7e0.png)

将save_zero去掉，在deepspeed.initialize(model...)后增加 model.save_zero_checkpoint = False，可以保存，但是保存后就卡住很久（1-2小时都不动了）
![image](https://user-images.githubusercontent.com/7539692/132816259-b12641fc-1cd0-4915-8e72-8a1728fef877.png)

麻烦看看，谢谢 @ t1101675

**Comment by t1101675** [comment]
您好，感谢关注！我们更新了一下镜像，上面 `save_zero` 的 bug 已经修复了。
