### ISSUE TITLE
请问可以不用deepspeed吗

### ISSUE THREAD

**Issue by 2020zyc** [TsinghuaAI/CPM-2-Finetune#18]
你好，对deepspeed不太熟悉，请问可以不用deepspeed吗？
我把4个模型文件合并成1个，用40g的A100加载成功（大概占用24G），这种情况下可以不使用deepspeed吗？
会导致显存急剧增加吗？
fp16是否可以单独设置呢？
是否有其他需要改变的设置？
期待回复，谢谢。
@t1101675

**Comment by t1101675** [comment]
您好，fp16 确实可以单独配置，将所有和 deepspeed 有关的东西注释掉就可以了。但是我们的 checkpoint 的格式是 deepspeed 保存下来的格式，如果不使用deepspeed可能就无法加载预训练的模型。

**Comment by 2020zyc** [comment]
谢谢回复。

还有个问题，请问可以 不使用 命令行式的 deepspeed launcher吗，例如cpm2/scripts/prompt/finetune_cpm2_wmt_cn.sh 
![image](https://user-images.githubusercontent.com/7539692/134861727-78cd74eb-f505-4234-a71b-3e3d044ae603.png)

我想在代码里面设置，比如设置4块gpu，模型并行度=4，然后让deepspeed加载模型；现在的问题是，这样的设置只能启动一个进程加载4个模型块中的一个（只看到一块gpu显存有点变化，所以我认为只启动了一个进程or线程），然后就卡住，无法加载完整的模型；

而命令行模式，一开始就能看到4块gpu都在加载模型块；

**Comment by t1101675** [comment]
您好，很抱歉没有看懂您的问题。首先，您说的命令行模式指什么？其次，到底是使用命令行模式出错，还是不使用命令行模式出错？您方面分享一下完整的脚本配置吗？这样有助于我们定位问题。

**Comment by 2020zyc** [comment]
> 您好，很抱歉没有看懂您的问题。首先，您说的命令行模式指什么？其次，到底是使用命令行模式出错，还是不使用命令行模式出错？您方面分享一下完整的脚本配置吗？这样有助于我们定位问题。

就是cpm目录下不是有script脚本，前面我都是用 
`bash script/fullmodel(或者prompt)/finetuen_xxx.sh`
 来启动的，sh脚本里面格式就是上面图片里的，最后实际执行 命令（即我说的命令行模式）
`deepspeed --num_nodes X --num_gpus Y fintune_cpm.py ......`
如果设置--num_gpus=4，那deepspeed的[launcher(launch.py)](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/launcher/launch.py)会启动4个进程并传入相应的localrank（0->3），如下；可以看到4块gpu都使用了并且使用情况差不多
![image](https://user-images.githubusercontent.com/7539692/135008183-dfbc62ca-4855-40d3-b887-554ab7d1e986.png)

我现在是想直接在代码里设置deepspeed的启动，就是不用上面的命令行模式（包括在代码里调用命令行执行）；这个想法是因为我可能用进程A创建进程B并让进程B启动整个CPM项目，所以希望能在代码里直接设置deepspeed的启动（不希望在进程B的代码里调用上述命令行启动CPM项目）；

遇到的问题：还是加载4个模型文件，但是现在只能启动一个进程，只占用1块gpu，无法像命令行模式一样能启动4个进程并使用4块gpu；最终无法完整加载4个模型文件得到完整模型，表现为卡住了，感觉像是唯一被创建的进程（比如对应模型文件0）在等其他3个进程加载相应的模型文件（对应模型文件1/2/3），但是根本没有其他3个进程被创建；

您有这方面的实现建议吗

**Comment by t1101675** [comment]
您好，请问您有没有试过直接使用 pytorch.distributed 启动代码呢？这个是 pytorch 提供的并行训练接口。我们只尝试过使用 deepspeed 启动或者使用 pytorch.distributed 启动

**Comment by 2020zyc** [comment]
> 您好，请问您有没有试过直接使用 pytorch.distributed 启动代码呢？这个是 pytorch 提供的并行训练接口。我们只尝试过使用 deepspeed 启动或者使用 pytorch.distributed 启动

谢谢回复。

没试过pytorch.distributed ，而且不是很熟悉🤦‍♀️。请问是类似deepspeed launcher的做法吗，在代码里用pytorch.distributed启动多进程，每个进程执行finetune_cpm.py并传入需要的参数？
