### ISSUE TITLE
显存占用

### ISSUE THREAD

**Issue by 2020zyc** [TsinghuaAI/CPM-2-Finetune#19]
你好，想问一下，设置模型并行度为4，gpu数量=4，然后加载4个模型文件，为啥跑起来后，4个GPU都是2/30g，按理说模型并行，不应该每块gpu是<10g的吗（模型整体大小24G，则4块并行的话，每块应该6g，加上运行过程中间量也不会达到2、30吧）；

上述情况看起来更像是4块gpu都拥有完整的整个模型。。。我也没多设置啥呀

谢谢
@t1101675

**Comment by t1101675** [comment]
您好，Transformer 运行时的现存占用比单纯模型的占用要多得多，主要来自三部分：运行时中间的 hidden state、反向传播时的梯度以及 Adam 优化器存储的动量等。这种现象在模型是混合精度时尤为明显，因为为了保证计算稳定性，优化器会保存一部分全精度参数，所以看起来比本身半精度的模型占用显存还多。这两篇论文 http://arxiv.org/abs/2104.07857 ，https://arxiv.org/abs/1910.02054 对模型运行时显存占用做了比较详尽的分析，可以作为参考。

**Comment by 2020zyc** [comment]
> 您好，Transformer 运行时的现存占用比单纯模型的占用要多得多，主要来自三部分：运行时中间的 hidden state、反向传播时的梯度以及 Adam 优化器存储的动量等。这种现象在模型是混合精度时尤为明显，因为为了保证计算稳定性，优化器会保存一部分全精度参数，所以看起来比本身半精度的模型占用显存还多。这两篇论文 http://arxiv.org/abs/2104.07857 ，https://arxiv.org/abs/1910.02054 对模型运行时显存占用做了比较详尽的分析，可以作为参考。

感谢回复。

我知道有中间量占用显存；我意思是 单模型（事先根据你们提供的脚本合并4个模型文件为一个，并设置并行度为1）单卡训练时，占用20-30G显存；单卡显存占用比较多所以想用模型并行减少每张卡占用，以便训练更长的序列；但是设置并行度为4并设置gpu数量=4时（模型使用你们给的4模型文件），每块gpu还是占用20+G甚至阶段性变成30+G；

后来我朋友把代码改了不少，同样并行度为4的情况，他每块gpu只使用7-8G，问他怎么做的，他说改了不少忘了。。。

模型并行直观上理解应该每块gpu只存储和运行部分模型参数、激活（训练时也只有这些参数的梯度和优化器参数），所以按理说应该是接近单模型单卡运行显存占用的1/4，但是我观察到的是并行度为4时，每块gpu显存占用还是和并行度为1时单gpu差不多，仿佛是在做数据并行。。。
