### ISSUE TITLE
the decoder input in evaluate_gen()

### ISSUE THREAD

**Issue by GMago123** [TsinghuaAI/CPM-2-Finetune#20]
Hi, there seems to be a problem in evaluate_gen() in finetune_cpm2.py.
In line 346: dec_input_ids = tokens_to_add.unsqueeze(-1)
The model decoder will only accept the last token as the decoder input in the iteration. However, usually, all generated tokens (in that function, it is variable 'output_ids') should be accepted as input of the decoder in the model.
Is there any bug?

**Comment by t1101675** [comment]
I don't think it's a bug. This is a trick to accelerate the generation of the model. The information of the previous tokens is input as the `past_key_values`, which is a cache of the 'K' and 'V' values of the Transformer at each layer. In this way, we don't need to recompute the representations of the output tokens.
