### ISSUE TITLE
模型fine-tune显存溢出

### ISSUE THREAD

**Issue by leecuijiao** [TsinghuaAI/CPM-2-Finetune#23]
请问CPM-2 100000模型微调需要多大显存，我在微调时使用8块12G显存的GPU，模型并行度为8，报显存溢出错误

**Comment by leecuijiao** [comment]
请问你们在训练时使用的GPU显存大小，块数，模型并行度分别是多少

**Comment by t1101675** [comment]
我们使用的是32G的显存，8卡，模型并行度是4

**Comment by Qnlp** [comment]
> 我们使用的是32G的显存，8卡，模型并行度是4

@t1101675 单机吗？我单机40G显存，8卡，模型并行度是4 ，显存溢出

**Comment by t1101675** [comment]
是单机。我们 batch size 是16~32 不等，对于比较长的输入可能要相应调小 batch size
