### ISSUE TITLE
怎么加入新词再finetune

### ISSUE THREAD

**Issue by LinglingGreat** [TsinghuaAI/CPM-2-Finetune#28]
如题，我想要在vocab.txt的基础上加入几个自定义的token，再进行finetune，但是直接修改vocab.txt会报错：
size mismatch for word_embeds.weight: copying a param with shape torch.Size([原来的token数, 2048]) from checkpoint, the shape in current model is torch.Size([新的token数, 2048]).
size mismatch for lm_head.weight
size mismatch for encoder.word_embeds.weight
size mismatch for decoder.word_embeds.weight

请问怎么才能加入自定义token而不报错呢？

**Comment by Qnlp** [comment]
resize模型的embedding，然后进行部分初始化一下，具体实现可以参考huggingface；没有在cpm2上试过 @LinglingGreat

**Comment by LinglingGreat** [comment]
huggingface是提供了相关的函数，所以知道怎么弄。但是cpm2貌似没提供这样的函数，不会。。。

**Comment by Qnlp** [comment]
仿写一个对应函数就好了
