### ISSUE TITLE
CPM2在生成任务上的微调策略

### ISSUE THREAD

**Issue by Qnlp** [TsinghuaAI/CPM-2-Finetune#29]
从这里下载的模型https://resource.wudaoai.cn/home?ind=2
，其余参数保持默认，在生成任务上，效果不太理想，可能会有哪些主要原因呢？

scripts/prompt/finetune_cpm2_adgen.sh 
```
NUM_WORKERS=1
NUM_GPUS_PER_WORKER=8
BATCH_SIZE=48
EVAL_BATCH_SIZE=32
```

**Comment by t1101675** [comment]
您说的效果不理想具体指什么？可以试试调整一下采样参数

**Comment by Qnlp** [comment]
@t1101675 对比了和mt5-base 的效果，有一定差距（有尝试采样参数）

**Comment by t1101675** [comment]
可以 show 一下具体的例子吗？以及运行的脚本？
