### ISSUE TITLE
Math23K 没有公开test_private.json 文件吗？

### ISSUE THREAD

**Issue by Qnlp** [TsinghuaAI/CPM-2-Finetune#34]

**Comment by t1101675** [comment]
http://cuge.baai.ac.cn/#/dataset?id=15&name=Math23K 看一下这里呢？

**Comment by Qnlp** [comment]
@t1101675 only test_public.json

**Comment by zzy14** [comment]
@Qnlp private是标准答案，CUGE作为评测应该是不提供的。
