### ISSUE TITLE
finetune的最小配置是？

### ISSUE THREAD

**Issue by eshaoliu** [TsinghuaAI/CPM-2-Finetune#4]
单机4卡，4*22G显存是否够用？

**Comment by t1101675** [comment]
Prompt Tuning 一些输入比较短的任务或许够用。但是 Finetune 全参数应该是不够用的。我们 Fine-tune 的配置统一都是2台机器，每台机器8卡32G V100

**Comment by eshaoliu** [comment]
好的，多谢解答

**Comment by eshaoliu** [comment]
> Prompt Tuning 一些输入比较短的任务或许够用。但是 Finetune 全参数应该是不够用的。我们 Fine-tune 的配置统一都是2台机器，每台机器8卡32G V100

顺便问下，你下载的CPM2模型有这个文件吗？latest_checkpointed_iteration.txt 我怎么只有4个.pt文件，finetune之前需要把这4个pt文件转为checkpoint文件吗？

**Comment by t1101675** [comment]
需要构造一下读入的目录，相关方法已经在 README 中更新。感谢提醒！

**Comment by eshaoliu** [comment]
> 需要构造一下读入的目录，相关方法已经在 README 中更新。感谢提醒！

好的

**Comment by t1101675** [comment]
我们对模型 prompt 微调的显存占用做了一点优化，现在确定 4*22G 显存可以跑起来 prompt 微调。不过需要注意调整 BATCH_SIZE 的大小或者梯度累计 GRAD_ACC 的大小，因为卡数变少之后相应数据并行数量减少，总 batch size 也会减少。

**Comment by lonelydancer** [comment]
4*32G v100, BATCH_SIZE=2, GRAD_ACC=1,依然跑不起来，不知道还需要设置哪些参数?
bash scripts/full_model/finetune_cpm2_math.sh 
RuntimeError: CUDA out of memory. Tried to allocate 1.86 GiB (GPU 1; 31.75 GiB total capacity; 29.82 GiB already allocated; 1.13 GiB free; 29.83 GiB reserved in total by PyTorch)

**Comment by t1101675** [comment]
full model 是全参数微调，需要用两台 8*32G V100，上面说的是 Prompt 微调，脚本在 prompt/ 里面
