### ISSUE TITLE
Docker DeepSpeed error: ssh: Could not resolve hostname node0: Name or service not known

### ISSUE THREAD

**Issue by sebastian-nehrdich** [TsinghuaAI/CPM-2-Finetune#42]
I am running into the following problem with DeepSpeed when running the docker image: 
`bash finetune_cpm2_wmt_cn.sh 
deepspeed --num_nodes 1 --num_gpus 1 --hostfile /mnt/configs/host_files/hostfile-cpm2 /mnt/finetune_cpm2.py --model-config /mnt/configs/model/cpm2_config.json --model-parallel-size 4 --batch-size 16 --gradient-accumulation-steps 2 --train-iters -1 --save /mnt/results/cpm2_finetune_wmtcn_lr0.000005const_G2/ --log-file /mnt/results/cpm2_finetune_wmtcn_lr0.000005const_G2//log.txt --load /root/thu-plm/checkpoints/cpm2-encn --data-path /root/thu-plm/data/wmt20-encn --data-ext .json --data-name wmtencn --distributed-backend nccl --lr 0.000005 --no-load-optim --lr-decay-style constant --weight-decay 1e-2 --clip-grad 1.0 --warmup 0.0 --tokenizer-path /mnt/bpe_cn_en --save-interval 100000 --eval-interval 1 --eval-iters 10 --log-interval 10 --checkpoint-activations --deepspeed-activation-checkpointing --fp16 --deepspeed --deepspeed_config /mnt/configs/deepspeed/ds_full_model.json --do_train --do_valid --epochs 1
ssh: Could not resolve hostname node0: Name or service not known
Traceback (most recent call last):
  File "/opt/conda/bin/deepspeed", line 6, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/launcher/runner.py", line 281, in main
    result = subprocess.check_output(hostname_cmd, shell=True)
  File "/opt/conda/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/conda/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ssh node0 hostname -I']' returned non-zero exit status 255.
`

**Comment by shanekong** [comment]
I encounter the same problem, have you found a way out?

**Comment by sebastian-nehrdich** [comment]
No, unfortunately not yet,

**Comment by shanekong** [comment]
i try to use torch torch.distributed.launch to start it, it works.
CMD="python -m torch.distributed.launch --nproc_per_node 8 --node_rank $1 --nnodes 2 --master_addr host_ip --master_port 25500 ${WORKING_DIR}/finetune_cpm2.py ${OPTS}"

**Comment by sebastian-nehrdich** [comment]
Thanks, this is great 👍

shanekong ***@***.***> schrieb am Mi., 7. Sept. 2022, 10:17
AM:
