### ISSUE TITLE
adgen数据集

### ISSUE THREAD

**Issue by zhenhao-huang** [TsinghuaAI/CPM-2-Finetune#5]
有`adgen`数据集的下载地址吗

**Comment by t1101675** [comment]
可以参考 http://cuge.baai.ac.cn/#/more?id=41

**Comment by zhenhao-huang** [comment]
thx.

**Comment by makeme-zgz** [comment]
貌似这个链接已经不提供adgen的数据集了？

**Comment by shanekong** [comment]
原始论文这里有-https://github.com/ZhihongShao/Planning-based-Hierarchical-Variational-Model
