### ISSUE TITLE
CPM-2-Finetuning的推理速度有多快(在V100上)

### ISSUE THREAD

**Issue by lonelydancer** [TsinghuaAI/CPM-2-Finetune#6]
你好，请问CPM-2-Fintuning在V100上的推理速度有多快。
如果模型不是Moe的话，也不能使用InfMoE做推理吧。

**Comment by arthfa** [comment]
有同学在A100 80GB上试过Moe-Fintune吗？需要多少GPU？

**Comment by Qnlp** [comment]
@arthfa moe 需要对应开发，你有跑起来吗？
我理解infomoe 只是推理，需要先适配才能推理。
