### ISSUE TITLE
deepspeed init hang住

### ISSUE THREAD

**Issue by lonelydancer** [TsinghuaAI/CPM-2-Finetune#7]
跑math23k数据集的时候，用单机4卡跑，会在deepspeed init时hang住；关闭deepspeed也一样。
请问配置需要注意什么吗?

![image](https://user-images.githubusercontent.com/548443/125922019-6d76608d-f31d-4659-aad8-d82543aae326.png)

**Comment by t1101675** [comment]
没有额外的配置了，可以检查一下 deepspeed、torch_distributed 的安装是否有问题，或者是一些运行过程中的锁没有被清掉之类的

**Comment by lonelydancer** [comment]
torch_distributed中master_adress &ip要配置一下就ok了。

**Comment by 2020zyc** [comment]
> torch_distributed中master_adress &ip要配置一下就ok了。

你好，请问关掉deepspeed能正常跑吗
