### ISSUE TITLE
MoE Finetune

### ISSUE THREAD

**Issue by lizy14** [TsinghuaAI/CPM-2-Finetune#9]
Thank you for your work. I'd ask about fine-tuning the MoE model. Did you do such experiments? If no, may I ask why? If yes, is there any plan to release source codes? Thanks!

**Comment by zzy14** [comment]
Hi,

Thanks for your question! We did try to fine-tune the MoE model and found it requires huge computation resources. To solve this problem, we are working on fine-tuning MoE models efficiently. If we have new progress on it, we will release the code as soon as possible.
